# Generated by Django 3.1 on 2020-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
