# Generated by Django 3.1.4 on 2020-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0002_auto_20201225_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
