# Generated by Django 3.1 on 2020-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0002_newspost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.TextField(max_length=100),
        ),
    ]
