# Generated by Django 3.1 on 2020-10-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0003_auto_20201004_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
